language: cpp
dist: xenial
compiler: gcc

before_install:
  - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
  - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update  -qq
install:
  - sudo apt-get install -qq g++-7
  - wget -c http://download.qt.io/official_releases/qt/5.13/5.13.0/qt-opensource-linux-x64-5.13.0.run
  - sudo chmod +x qt-opensource-linux-x64-5.13.0.run
  - sudo chmod +x ./extract-qt-installer ./install-qt
  - sudo ./install-qt
  - sudo apt-get install build-essential libfontconfig1 mesa-common-dev libglu1-mesa-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
script: 
  - mkdir -p build
  - cd build
  - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_BUILD_TYPE=Coverage -DBUILD_TESTS=ON ..
  - make --silent
  - ctest
